# Generated by Django 5.1.5 on 2025-10-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catblog',
            name='descriptions',
            field=models.TextField(max_length=10000),
        ),
    ]
