# Generated by Django 5.1.5 on 2025-10-25 10:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_catblog_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catblog',
            name='descriptions',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=10000),
        ),
    ]
